apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-web-app
  name: nginx-web-app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30089
  selector:
    app: nginx-web-app
  type: NodePort
